---

- name: Create mapping between IP and hostname for HANA VMs
  run_once: true
  set_fact:
    hanadbnodes_dict: "{{ hanadbnodes_dict | combine({item.ip_admin_nic : item.dbname}) }}"
  loop: "{{ hana_database.nodes }}"

- name: Check DHCLIENT_SET_HOSTNAME settings
  shell: grep DHCLIENT_SET_HOSTNAME= /etc/sysconfig/network/dhcp
  register: dhcp_res

- debug:
    msg: "{{ dhcp_res }}"

- name: Check if the correct hostnames are set on HANA VMs
  fail:
    msg: "Hostname is not set properly for {{ inventory_hostname }}: should be {{ hanadbnodes_dict[inventory_hostname] }} but seen {{ ansible_hostname }}"
  when: ansible_hostname != hanadbnodes_dict[inventory_hostname]
