# This Azure pipeline YAML is a step template that will perform:
# - Logon to rti
# - Continue deployment with Ansible for the current test case

parameters:
#####################################################################
# Eg:  testCaseName: current test case name eg: sap-reuseVNET-777    #
#                                                                   #
# For all possible values, please refer to:                         #
# - azure-pipelines-daily.yaml                                   #
# - sap-hana/templates/README.MD                                    #
#                                                                   #
#####################################################################
    testCaseName: ''
steps:
  - script: |
      az login --service-principal --user $(hana-pipeline-spn-id) --password  $(hana-pipeline-spn-pw) --tenant $(landscape-tenant) --output none
      az network vnet subnet update -g ${{parameters.testCaseName}} -n subnet-mgmt --vnet-name vnet-mgmt --network-security-group nsg-mgmt --output none
      az network vnet subnet update -g ${{parameters.testCaseName}} -n subnet-admin --vnet-name vnet-sap --network-security-group nsg-admin --output none
      az network vnet subnet update -g ${{parameters.testCaseName}} -n subnet-db --vnet-name vnet-sap --network-security-group nsg-db --output none
    displayName: 'Update NSG for subnets'
  - script: |
      echo "Ansible Deployment in progress..."
      cd deploy/terraform/default/ansible_config_files
      rti_user=$(cat output.json | jq -r '.jumpboxes.linux[] | select(.destroy_after_deploy == "true") | .authentication.username')
      rti_public_ip=$(cat output.json | jq -r '.jumpboxes.linux[] | select(.destroy_after_deploy == "true") | .public_ip_address')
      ssh -i /tmp/sshkey -o StrictHostKeyChecking=no "${rti_user}"@"${rti_public_ip}" '
      ansible-playbook --version
      export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
      export ANSIBLE_HOST_KEY_CHECKING=False
      source export-clustering-sp-details.sh
      ansible-playbook -i hosts.yml sap-hana/deploy/ansible/sap_playbook.yml
      '
    displayName: 'Ansible Deployment'
    env:
      TF_VAR_azure_service_principal_id: $(hana-pipeline-spn-id)
      TF_VAR_azure_service_principal_pw: $(hana-pipeline-spn-pw)
      AZURE_CLIENT_ID: $(hana-pipeline-spn-id)
      AZURE_SECRET: $(hana-pipeline-spn-pw)
      AZURE_TENANT: $(landscape-tenant)
      AZURE_SUBSCRIPTION_ID: $(landscape-subscription)
      ARM_CLIENT_ID: $(hana-pipeline-spn-id)
      ARM_CLIENT_SECRET: $(hana-pipeline-spn-pw)
      ARM_TENANT_ID: $(landscape-tenant)
      ARM_SUBSCRIPTION_ID: $(landscape-subscription)
      ANSIBLE_CONDITIONAL_BARE_VARS: false  # supresses conditional bare variables deprecation warning
