parameters:
  osVersion: ''
  osImage: ''

jobs:
- job: createAllNew_SN_${{parameters.osVersion}}
  timeoutInMinutes: 180
  variables:
    scenario: sap-allNew-SN
    testcase: $(scenario)-${{parameters.osVersion}}-$(Build.BuildId)
  steps:
  - template: test-case-template-update.yaml
    parameters:
      scenario: $(scenario)
      testCaseName: $(testcase)
      placeHolder: var-rg-name
      value: $(testcase)
  - template: terraform-deployment-steps-hrs.yaml
    parameters:
      testCaseName: $(testcase)
      osImage: ${{parameters.osImage}}
  - template: ansible-deployment-steps-hrs.yaml
    parameters:
      testCaseName: $(testcase)
- job: createAllNew_HA_${{parameters.osVersion}}
  timeoutInMinutes: 180
  variables:
    scenario: sap-allNew-HA
    testcase: $(scenario)-${{parameters.osVersion}}-$(Build.BuildId)
  steps:
  - template: test-case-template-update.yaml
    parameters:
      scenario: $(scenario)
      testCaseName: $(testcase)
      placeHolder: var-rg-name
      value: $(testcase)
  - template: terraform-deployment-steps-hrs.yaml
    parameters:
      testCaseName: $(testcase)
      osImage: ${{parameters.osImage}}
  - template: ansible-deployment-steps-hrs.yaml
    parameters:
      testCaseName: $(testcase)
